version: "3.8"
services:
  xgproyect_v3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/upload:/var/www/html
    depends_on:
      - db
    networks:
      - xgp_network
      - docker_backend
  db:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - xgp_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
    networks:
      - docker_backend
      - xgp_network

networks:
    xgp_network:
    docker_backend:
      external: True
